version: "3"

services:
  web-sever:
    image: nginx:1.27-alpine
    ports:
      - 9000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/test_app

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/test_app
    depends_on:
      - web-sever

  db:
    image: mysql:8.0
    container_name: db_container
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_db_password
      MYSQL_ROOT_PASSWORD: test_db_root_password
    ports:
      - 3308:3306
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_container
    ports:
      - 8081:80
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: test_db_root_password

volumes:
  db_data:
